### ISSUE TITLE
feat: add date schema

### ISSUE THREAD

**Issue by chen1415** [chen1415/extra-data-types#14]
### Description

add data schema and specify some data types.
For e.g, DateSchema.DateStringWithUtc

### Solution

PR is welcome~

**Comment by IAmJerryJ** [comment]
**Solution**
Add new date types and tests

Steps:
1. Create date folder
2. Add date regex expression of date format
3. Add date types typescript file with regex expression
4. Add unit tests

**Comment by chen1415** [comment]
no need to write this. you can just say what you want to do here:
for example, I want to add date type of UTF.
and give an example

**Comment by chen1415** [comment]
YYYY-MM-DD : 1999-09-19
YYYY-MMM-DD: 1999-Feb-09
