### ISSUE TITLE
feat:  more types

### ISSUE THREAD

**Issue by chen1415** [chen1415/extra-data-types#39]
Maybe more types are needed? for date, time and datetime?

Also readme need to be updated to make it more clear to read :)

**Comment by IAmJerryJ** [comment]
Update naming convention in README.md

**Comment by chen1415** [comment]
I think need other types for Date Type first. Check here
https://zh.wikipedia.org/wiki/%E5%90%84%E5%9C%B0%E6%97%A5%E6%9C%9F%E5%92%8C%E6%97%B6%E9%97%B4%E8%A1%A8%E7%A4%BA%E6%B3%95

may be dd-mm-yyyy and dd-mm-yy first？
