### ISSUE TITLE
bug in documentation: what is QQ Mail?  

### ISSUE THREAD

**Issue by ChaimStanton** [chen1415/extra-data-types#50]
Line 45 of the [readme](https://github.com/chen1415/extra-data-types/blob/95d2a13f9e78992454f97961e7e2fd7a9facf540/README.md) mentions a a 'QQmail', however it isn't clear what a 'QQmail' is. 

Furthermore an example is not given around line 16.
```
Email:

| Email Schema  | Type_Name          | Function              | :white_check_mark: | :x:         |
| ------------- | ------------------ | --------------------- | ------------------ | ----------- |
| StandardEmail | StandardEmail_Type | is_StandardEmail_Type | abc@abc.com        | abc         |
| QQMail        | QQmail_Type        | is_QQmail_Type        | 123@qq.com         | a@a.com     |
| Gmail         | Gmail_Type         | is_Gmail_Type         | a@gmail.com        | a@cmail.com |
```

**Comment by chen1415** [comment]
HaHa. 
QQmail is a popular mail format in CHINA. As far as I know, basically every Chinese people have a QQ number and it along with a QQmail. which is like this usually.
1234567822@qq.com or ramdom@qq.com

just like gmail is xxx@gmail.com QQ mail is xxx@qq.com.
[QQ](https://qqmail.info/)

**Comment by chen1415** [comment]
Thanks for your reply! Really appreciate on it!
